<?php
namespace ut8ia\medicine\models\forms;

use ut8ia\medicine\models\ExpertGroups;
use ut8ia\medicine\models\Experts;
use ut8ia\medicine\models\ExpertsIdentity;
use ut8ia\medicine\models\Places;
use Yii;

/**
 * Class PlacesForm
 * @package ut8ia\medicine\models\forms
 */
class ExpertsForm extends Experts
{


    public $newPassword;

    public function formName()
    {
        return "expertsForm";
    }

    public function rules()
    {
        $rules = parent::rules();
        $rules[] = ['newPassword', 'string'];
        return $rules;
    }


    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            // if pass not empty - update it and set "must change" flag
            if (!empty($this->newPassword)) {

                if ($expertIdentity = ExpertsIdentity::findIdentity($this->id)) {
                    $expertIdentity->setPassword($this->newPassword);
                    $expertIdentity->password_change = ExpertsIdentity::PASSWORD_NEED_CHANGE;
                    $expertIdentity->save();
                }

            };
            return true;
        }
        return false;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $this->unlinkAll('places', true);
        $places = Yii::$app->request->post()[$this->formName()]['places'];
        if (!empty($places)) {
            foreach ($places as $place) {
                $this->link('places', Places::findOne($place));
            }
        }

        $this->unlinkAll('expertGroups', true);
        $groups = Yii::$app->request->post()[$this->formName()]['expertGroups'];
        if (!empty($groups)) {
            foreach ($groups as $group) {
                $this->link('expertGroups', ExpertGroups::findOne($group));
            }
        }

    }


}